### ISSUE TITLE
[JC64Dis] Don't add .org $07ff to source

### ISSUE THREAD

**Issue by rmoritz** [ice00/jc64#1]
dasm produces garbage unless I remove the following 3 lines that JC64Dis adds to the top of the source, immediately before the `.org $0801` proper.

```asm
  .org $07FF

  .byte 1
  .byte 8
```
Could you include an option to disable generation of this header code?

**Comment by ice00** [comment]
This behaviour was intended for being used with -f3 option of Dasm (otherwise you cannot produce back a PSID file being disassembled, so for PRG the starting address were added by disassembler itself).

This option is already planned with the adding support for other compilers

Thanks

**Comment by ice00** [comment]
Option added
