### ISSUE TITLE
[JC64Dis] Feature requests

### ISSUE THREAD

**Issue by rmoritz** [ice00/jc64#2]
Some small features that would make life easier:

1. Double-click on address in memory area scrolls to address in preview area (and source area?)
1. Selecting address range in preview area also selects addresses in memory area.
1. Add keyboard shortcuts for functions in Source menu, esp. *Find memory address*, *Find text in preview* and *Find text in source*.

**Comment by ice00** [comment]
1) In source area should be done only on address where a label is defined (or jump to the nearest label) and in preview not is data area (unless it has a label, or the nearest one)

2) This will be probably on the next commit

3) in actual source tar-ball all menus have a shortcuts

**Comment by ice00** [comment]
All implemented into current source.

Double click in memory now active only in preview.
Now sure if it can be useful even for source.

**Comment by rmoritz** [comment]
Just cloned the repo and built with Netbeans. Double-click in memory & preview selection work nicely :+1: Also, thanks for adding the hints to the menu for the kbd shortcuts.
