### ISSUE TITLE
[JC64Dis] Feature request: delete labels into areas marked as junk

### ISSUE THREAD

**Issue by rmoritz** [ice00/jc64#3]
Hey,

in the latest version I can mark regions as junk, which is super useful :+1: . However, dangling labels into the junk remain, which I then need to find & replace after saving the generated code, e.g. if I disassemble from $8000 to $CFFF, but actually didn't mean to include the BASIC ROM, then I can mark $A000 to $BFFF as junk, but labels like WAB47 remain. It would be great if they could be automagically replaced by their memory addresses, or if there were at least some manual way to delete the lables, short of having to start the disassembly again (I have lots of user comments and fixed lots of data areas).

Thanks and keep up the great work!

**Comment by ice00** [comment]
The solution is probably the one to automatically delete labels when marking the memory as junk and modify the automatic labelling to being disable when managing a memory address on junk area.

Actually you cannot delete such labels by hand as the engine will recreate them at next compilation.

**Comment by ice00** [comment]
Modification done

**Comment by rmoritz** [comment]
> Modification done

Just tested it with a memory dump from VICE monitor from $8000 to $cfff; after I marked $a000 to $bfff as junk and all WA??? labels were replaced with their addresses. Excellent! Thank you very much, Sir! :+1: :clap:
