### ISSUE TITLE
Need option to turn off the address modes.

### ISSUE THREAD

**Issue by deathybrs** [ice00/jc64#4]
In the first disassembly I am doing while testing out your (freaking AWESOME) tool, I found that I cannot turn off "+" mode after the initial disassembly decides it.  Am I missing something, or is the tool?

**Comment by deathybrs** [comment]
Though it does seem possible to work around it by switching the address to <# mode.

**Comment by deathybrs** [comment]
Whoops, sorry... not used to the github ticketing, didn't mean to close it.

**Comment by ice00** [comment]
The tool recalculate the (automatic) + address at every compilation, so if nothing is changed (eg. an area from code become of data type), if you delete it, it will be recreated.

The idea is that if the label points inside an instruction, you cannot label it unless you use the +1/+2

Example:

`
    LDA   #$22
    STA    Pippo+2

Pippo:
    LDA   $1122
`

However you should be able to change it in:

`
    LDA   #$22
    STA   Pluto-1

    LDA   $1122
Pluto:
`

However, let me show an example on where it is necessary to bypass this rule. In that case I wil lstudy a solution for this.

Thanks

**Comment by deathybrs** [comment]
I'll see if I can find a good reliable example.  It seems that sometimes it switches back to + even when it's memory locations, but I have not identified a specific way to demonstrate why/when it does this yet.

**Comment by ice00** [comment]
If you are able to reproduce it, then there should be a bug for sure:

The routine looks if a memory location inside an instruction of 3 bytes (so with an word address operand) has an automatic label defined. In that case it adds the + to it.

The label in that memory location is defined automatically if there was an instruction in other part that points to it. If you switch from code to data where there is the +, the label still remain there, but there is a global option to cancel the + during this operation (for default it is on), so the + should be erased automatically and no more created as now that part is of data.

**Comment by deathybrs** [comment]
I'm not getting it to happen again in what I'm analyzing, I'll go ahead and close this.

Thanks!

**Comment by ice00** [comment]
However it not accept the change from a + address to a - address as I was supposing it does
